services:
  test_web:
    build: .
    ports:
      - "${APP_PORT:-5100}:5000"
    env_file:
      - .env.test
    depends_on:
      - test_db
  
  test_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


